server:
  context-path: /
  port: 8090
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch #默认即为 elasticsearch
      cluster-nodes: 139.199.36.66:9200 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode